### ISSUE TITLE
Crontab consistency

### ISSUE THREAD

**Issue by michelesr** [amelbakry/kube-schedule-scaler#2]
As far as I can understand `clear_cron()` will commit the deletion before the rest of the code can determine the new jobs and commit them. This might lead to the following issues:

- if something fails in the code (such as an uncaught exception), the crontab will be totally blank and lose also the old rules
- there's a period of time between the execution of `clear_cron()` and the rest of the code in which the crontab is empty: what happens to the jobs that are supposed to run exactly in the moment the crontab is temporarily empty?

Wouldn't it be better to share a global instance of the crontab object and commit the changes only at the end? Possibly there must be a way to design this so that a single syntax error won't compromise the integrity of the whole crontab.

**Comment by michelesr** [comment]
```python
>>>  t = crontab.CronTab(user='root') 
>>> j = t.new(command='/usr/bin/echo')
>>> j
<CronItem '* * * * * /usr/bin/echo'>
>>> j.setall('20 3 * * *')
>>> j
<CronItem '20 3 * * * /usr/bin/echo'>
>>> j.setall('20 3 * * Mon-Fri')
>>> j.setall('20 3 * * *')
>>> j.setall('20 3 * * Mon-Fri')
>>> j.setall('20 3 * * Mon-Fra')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1153, in parse_value
    out = get_cronvalue(val, self.enum)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1177, in get_cronvalue
    return CronValue(unicode(value), enums)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1184, in __init__
    self.value = enums.index(value.lower())
ValueError: 'fra' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 707, in setall
    return self.slices.setall(*args)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 927, in setall
    set_a.parse(set_b)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1063, in parse
    self.parts += self.get_range(part)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1122, in get_range
    ret = CronRange(self, *vrange)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1227, in __init__
    self.parse(vrange[0])
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1250, in parse
    self.vto = self.slice.parse_value(vto)
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 1155, in parse_value
    raise ValueError("Unrecognised %s: '%s'" % (self.name, val))
ValueError: Unrecognised Day of Week: 'Fra'
```
So any syntax error is likely to be raised before running `write()`, so I guess is safe to just ignore (and raise a warning) those schedules that have a syntax error, and delay the `write()` operation until the very end, effectively treating the whole scheduling as a atomic transaction.

**Comment by michelesr** [comment]
This is a possible way to implement it: https://github.com/citizensadvice/kube-schedule-scaler/commit/66d816195fc1ea639128a227af411a293bef105b (our fork doesn't have stack sets, we only deal with deplyoments and hpas)

**Comment by amelbakry** [comment]
@michelesr Thanks a lot for your feedback.
- I caught the exception of wrong cron in this block
```            try:
                job.setall(schedule)
                job.set_comment("Scheduling_Jobs")
                scaling_cron.write()
            except Exception:
                print('Deployment: %s has syntax error in the schedule' % (deployment))
                pass```

**Comment by amelbakry** [comment]
So only the wrong cron will be missed also it will be logged for debugging.
- Regarding conflicts between the main cron and other created crons if they are in the same minute.
I handle this, the main cron executes every 3 minutes in the first second.and every sub cron will be executed (at the 50th second).

``` sleep 50```

**Comment by michelesr** [comment]
How do you know that it runs at the 50th second?

**Comment by amelbakry** [comment]
cmd = ['sleep 50 ; . /root/.profile ; /usr/bin/python', script_creator.name,
                   '2>&1 | tee -a /tmp/scale_activities.log']

**Comment by michelesr** [comment]
Great! I'll close the issue, as it seems that you have handled the problem already.
